### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by simnalamburt** [devsisters/eclair#11]
Eclair is awesome and more people should be able to easily receive grace of it. To do so, we need to package this and (maybe) automate the release process.

### TODOs
- [ ] [brew](https://brew.sh/)
- [ ] [Archlinux AUR](https://aur.archlinux.org/)
- [ ] `.rpm` using [copr](https://copr.fedorainfracloud.org/)
- [ ] `.deb` using [launchpad](https://launchpad.net/)
