### ISSUE TITLE
Deprecate 'config.aws_region' option and add 'config.default_aws_region' option.

### ISSUE THREAD

**Issue by simnalamburt** [devsisters/eclair#7]
`config.aws_region` overrides `AWS_REGION` environment variable, and changing config variables in `~/.ecl/config.rb` is not ergonomically convenient. So many users just comment out the `config.aws_region` variable and use the use the `AWS_REGION`.

So let's add new configuration option named `config.default_aws_region` which does not overrides `AWS_REGION` environment variable, and deprecate `config.aws_region` option.

### TODOs
- [ ] Remove `config.aws_region` option from documentation and eclare config template.
- [ ] Print a warning to the STDERR when `config.aws_region` variable is set by the user.
- [ ] Implement new `config.default_aws_region` option and mention it on docs and config template file.
